name: Pipeline CI - Calculadora com Matrix

on:
  push:
    branches: [main]

jobs:
  teste:
    name: Teste - ${{ matrix.os }} - Python ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-26.04

        python-version:
          - "3.11"
          - "3.12"

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Mostrar ambiente
        run: |
          echo "Sistema operacional:"
          lsb_release -a

          echo "Versão do Python:"
          python --version

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Análise de código - Flake8
        run: |
          flake8 calculadora.py test_*.py

      - name: Testes unitários
        run: |
          pytest test_*.py

      - name: Cobertura de código
        run: |
          pytest --cov=calculadora \
            --cov-report=term-missing \
            --cov-fail-under=80

      - name: Análise de segurança - Bandit
        run: |
          bandit -r calculadora.py

      - name: Verificar chaves de API expostas
        run: |
          if grep -R -nE "API_KEY[[:space:]]*=[[:space:]]*['\"][^'\"]+['\"]" . \
            --exclude-dir=.git \
            --exclude=pipeline.yml; then

            echo "ERRO: Chave de API encontrada!"
            exit 1

          else
            echo "Nenhuma chave de API encontrada."
          fi

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}